version: "3"
services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5556:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    tty: true
    restart: always
    user: root
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro